### ISSUE TITLE
Apple Mach-O Linker Errors

### ISSUE THREAD

**Issue by pejalo** [couchbaselabs/CouchbaseLiteViewer#12]
I'm messing with Xcode settings tying to get this to work, going down the same route as #7 #8 #9

Here's another error I'm getting:
![screen shot 2015-06-26 at 23 18 02](https://cloud.githubusercontent.com/assets/6892407/8390266/1384c6a8-1c5a-11e5-9a03-d287230102f3.png)

OSX Yosemite 10.10.3
Xcode 6.3.2
Couchbase Lite 1.1.0-31

**Comment by snej** [comment]
It's looking for symbols in the Security and SystemConfiguration frameworks but not finding them. But the app itself shouldn't need those frameworks; Couchbase Lite does, but it's a dynamic library on OS X so it doesn't affect the app's imports.

I'm guessing you are maybe trying to link with the _iOS_ CouchbaseLite framework.

**Comment by snej** [comment]
Yeah, I don't get these errors. Pretty certain you copied the wrong framework into the Frameworks folder.

**Comment by pejalo** [comment]
Yep, you were right. I got the OSX framework and it builds fine now. Thanks
