### ISSUE TITLE
Cannot select a database

### ISSUE THREAD

**Issue by jamiltz** [couchbaselabs/CouchbaseLiteViewer#13]
When selecting a database created with CBL 1.1 the following pops up:

<img width="1072" alt="screen shot 2015-07-15 at 14 26 36" src="https://cloud.githubusercontent.com/assets/2589337/8699483/aa390a30-2afd-11e5-9639-12331ad9ac50.png">

**Comment by goncalvesa** [comment]
Any update on this issue? Do you have a workaround for viewing / editing databases?

**Comment by ryanthompson0123** [comment]
Same issue here. Any updates?

**Comment by dinoka** [comment]
Same issue.

**Comment by amg1976** [comment]
Thanks for the fix.

**Comment by jamiltz** [comment]
closing this as it was fixed in the last release.
