### ISSUE TITLE
The Viewer don't support Couchbase Lite 1.2

### ISSUE THREAD

**Issue by atom992** [couchbaselabs/CouchbaseLiteViewer#21]
When I open a Couchbase Lite 1.2 file(Android),the following message showed:
```
The document “cbldb.cblite2” could not be opened. This database is too new to be opened by this app. Use a Viewer that supports Couchbase Lite 1.2.
```

**Comment by jadsonlourenco** [comment]
+1

**Comment by snej** [comment]
As a workaround, if you check out and build the viewer yourself, linking it with Couchbase Lite 1.2, it should work fine with 1.2 databases.

**Comment by atom992** [comment]
ok,Thank you ,I will try.

**Comment by atom992** [comment]
It works. thank you.

**Comment by snej** [comment]
What version of the viewer were you running before? I just noticed that there is a [release 0.62 for Couchbase Lite 1.2](https://github.com/couchbaselabs/CouchbaseLiteViewer/releases/tag/untagged-fa4bdda111f722e8526c). That one should work with 1.2 databases.

**Comment by atom992** [comment]
There is no link for tag 0.62. but when I  linking it with Couchbase Lite 1.2,It works. 
I will close this issue.
