### ISSUE TITLE
Android CBLIte 1.2 Support

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbaselabs/CouchbaseLiteViewer#23]
Latest version cant open CBLite 1.2 Android database. Screenshot attached.

<img width="420" alt="screen shot 2016-06-02 at 4 39 03 pm" src="https://cloud.githubusercontent.com/assets/1885940/15743059/8c4aaaf6-28e0-11e6-9832-aa1a6bb1a78e.png">

**Comment by tikimcfee** [comment]
Giving this a +1. Trying to test 1.1.0 migrations to 1.2.1, can't view the DB files to check data integrity.

**Comment by pradipvaghasiya** [comment]
This works with latest code and framework.
