### ISSUE TITLE
Remove 32-bit build setting

### ISSUE THREAD

**Issue by fakeh** [couchbaselabs/CouchbaseLiteViewer#8]
"-fobjc-arc is not supported with fragile abi"
Turning off Automatic Reference Counting in Build Settings allowed me past this step.

**Comment by snej** [comment]
The app shouldn't be built 32-bit; sounds like the build settings need to be updated to make it 64-bit only.

It might run with ARC turned off, but it'll leak memory like a sieve because there are no -release calls.

**Comment by snej** [comment]
The current build settings are "Standard Architectures (64-bit)" so this got fixed already at some point.
